name: bloc-inspector-client
base: core18
version: 0.0.1+1
summary: Investigate or Inspect Flutter BLoCs.
description: |
  Observe transition of events and state mutations in your BLocs to easily trace those annoying little bugs.
  See how your BloCs behave in real-time.

grade: devel
confinement: strict

apps:
  bloc-inspector-client:
    command: bloc_inspector_client
    extensions: [flutter-master]
    plugs:
      - network
    slots:
      - dbus-bloc-inspector-client

parts:
  bloc-inspector-client:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
